version: "3.7"

volumes:
  mysql-data:

services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./src:/var/www/html:cached
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
  php:
    build:
      context: .docker/php
      dockerfile: php.local.dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
